### ISSUE TITLE
Add condor support in gwdetchar-omega

### ISSUE THREAD

**Issue by alurban** [gwdetchar/gwdetchar#143]
In `gwdetchar-omega` there needs to be support for running on batch mode. This could be done using a `--batch` command line option that, when invoked, sets up (and potentially submits) the necessary jobs to Condor.

Note, there is currently a `--condor` option that does nothing.

**Comment by duncanmmacleod** [comment]
@alurban, given that `gwdetchar-omega` doesn't currently support processing multiple scans serially, I think it would be best to leave batch processing (including via condor) to a separate utility. Given that this functionality exists in `wdq-batch`, we can easily repurpose that script as `gwdetchar-omega-batch` or similar. I think this would be a cleaner solution.

**Comment by alurban** [comment]
@duncanmmacleod, I'm quite happy with that solution. This begs the question of what our ultimate plans are for `wdq`: namely, do we want to keep that script when we package `gwdetchar`, or deprecate it? If the former (which is likely given that other tools invoke `wdq` to produce omega scans), then I'll work to make `gwdetchar-omega` its default executable and refactor some of the functions defined in `gwdetchar-omega` into `gwdetchar.omega.scan`.

**Comment by duncanmmacleod** [comment]
@alurban, I would like to deprecate it slowly, as follows:

- add option to `wdq` to call out to `gwdetchar-omega` instead of `wpipeline`, with a `DeprecationWarning` suggesting that the default will change to `gwdetchar-omega` soon
- update `wdq` to default to `gwdetchar-omega`, and update `DeprecationWarning` to inform that this script will be removed in a future release
- remove `wdq`

**Comment by alurban** [comment]
@duncanmmacleod, sounds like a great plan to me!
