### ISSUE TITLE
Update default network scans 

### ISSUE THREAD

**Issue by jessmciver** [gwdetchar/gwdetchar#379]
`gwdetchar-omega -i Network` currently points to `/home/detchar/etc/omega/ER8/Network.ini` by default - perhaps this should be a public url instead? 

To first order, Greg Ashton noted that this file doesn't exist on LHO, and Derek Davis noticed it currently has the `state-flag` option enabled, which gave some confusing output if you're not expecting a segment check.  Perhaps this should be commented out of the default ini file with a brief explanation?

**Comment by alurban** [comment]
Thanks @jessmciver, by default the `gwdetchar-omega` tool assumes you're running on an LDAS cluster with configurations saved under a user account called `detchar`, the problem was that one of them didn't have an expected folder for ER8 (which I've just corrected). At any rate, custom configurations are always an option, which Greg was quickly able to switch to.

As to the `state-flag` issue, there is a command-line option to globally disable checks for active data-quality flags called `--ignore-state-flags`, see the help documentation:

```bash
$ gwdetchar-omega --help
```

It seems this resolves Greg's issues, so I'm going to go ahead and close the ticket.
